name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
    - name: Clang Code Formatter
      uses: ivanludvig/clang-format-action@v1.4
      env:
        GITHUB_TOKEN: ${ { secrets.GITHUB_TOKEN } }
        
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
        
      - name: Run tests
        run: |
            build/test/test --gtest_output="xml:report.xml"
            tree
            
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: report.xml
