name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  format:
    name: Format checker
    runs-on: ubuntu-latest
    container: yaishenka/docker-codestyle-checker
    steps:
      - uses: actions/checkout@v2
      - name: Start checking
        run: echo checking


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Format checker
#        uses: yaishenka/docker-codestyle-checker@master
#      - name: Apply format
#        run: |
#          git fetch
#          git diff -U0 --no-color main | clang-format-diff -p1 -style file | tee format_diff.diff
#          if [[ -s format_diff.diff ]]; then false; fi
#          dir
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .  
      - name: Run tests
        run: |
            build/test/test --gtest_output="xml:report.xml"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: report.xml
